export const careers = [
  {
    id: 1,
    code: "001",
    name: "ADMINISTRACIÓN",
    faculty: null,
  },
  {
    id: 2,
    code: "002",
    name: "ANTROPOLOGÍA",
    faculty: null,
  },
  {
    id: 3,
    code: "003",
    name: "ARQUITECTURA Y URBANISMO",
    faculty: null,
  },
  {
    id: 4,
    code: "004",
    name: "ARTE",
    faculty: null,
  },
  {
    id: 5,
    code: "008",
    name: "BIOLOGÍA",
    faculty: null,
  },
  {
    id: 6,
    code: "011",
    name: "CIENCIAS CONTABLES",
    faculty: null,
  },
  {
    id: 7,
    code: "012",
    name: "CIENCIAS DE LA COMUNICACIÓN SOCIAL",
    faculty: null,
  },
  {
    id: 8,
    code: "013",
    name: "CIENCIAS FÍSICO MATEMÁTICAS",
    faculty: null,
  },
  {
    id: 9,
    code: "015",
    name: "DERECHO",
    faculty: null,
  },
  {
    id: 10,
    code: "034",
    name: "EDUCACIÓN FÍSICA",
    faculty: null,
  },
  {
    id: 11,
    code: "035",
    name: "EDUCACIÓN INICIAL",
    faculty: null,
  },
  {
    id: 12,
    code: "036",
    name: "EDUCACIÓN PRIMARIA",
    faculty: null,
  },
  {
    id: 13,
    code: "037",
    name: "EDUCACIÓN SECUNDARIA",
    faculty: null,
  },
  {
    id: 14,
    code: "041",
    name: "ENFERMERÍA",
    faculty: null,
  },
  {
    id: 15,
    code: "042",
    name: "INGENIERÍA AGRÍCOLA",
    faculty: null,
  },
  {
    id: 16,
    code: "043",
    name: "INGENIERÍA AGROINDUSTRIAL",
    faculty: null,
  },
  {
    id: 17,
    code: "044",
    name: "INGENIERÍA AGRONÓMICA",
    faculty: null,
  },
  {
    id: 18,
    code: "045",
    name: "INGENIERÍA CIVIL",
    faculty: null,
  },
  {
    id: 19,
    code: "046",
    name: "INGENIERÍA DE MINAS",
    faculty: null,
  },
  {
    id: 20,
    code: "047",
    name: "INGENIERÍA DE SISTEMAS",
    faculty: null,
  },
  {
    id: 21,
    code: "048",
    name: "INGENIERÍA ECONÓMICA",
    faculty: null,
  },
  {
    id: 22,
    code: "049",
    name: "INGENIERÍA ELECTRÓNICA",
    faculty: null,
  },
  {
    id: 23,
    code: "050",
    name: "INGENIERÍA ESTADÍSTICA E INFORMÁTICA",
    faculty: null,
  },
  {
    id: 24,
    code: "051",
    name: "INGENIERÍA GEOLÓGICA",
    faculty: null,
  },
  {
    id: 25,
    code: "052",
    name: "INGENIERÍA MECÁNICA Y ELECTRICA",
    faculty: null,
  },
  {
    id: 26,
    code: "053",
    name: "INGENIERÍA METALÚRGICA",
    faculty: null,
  },
  {
    id: 27,
    code: "054",
    name: "INGENIERÍA QUÍMICA",
    faculty: null,
  },
  {
    id: 28,
    code: "055",
    name: "INGENIERÍA TOPOGRÁFICA Y AGRIMENSURA",
    faculty: null,
  },
  {
    id: 29,
    code: "169",
    name: "MEDICINA HUMANA",
    faculty: null,
  },
  {
    id: 30,
    code: "170",
    name: "MEDICINA VETERINARIA Y ZOOTECNÍA",
    faculty: null,
  },
  {
    id: 31,
    code: "171",
    name: "NUTRICIÓN HUMANA",
    faculty: null,
  },
  {
    id: 32,
    code: "172",
    name: "ODONTOLOGÍA",
    faculty: null,
  },
  {
    id: 33,
    code: "231",
    name: "SOCIOLOGÍA",
    faculty: null,
  },
  {
    id: 34,
    code: "232",
    name: "TRABAJO SOCIAL",
    faculty: null,
  },
  {
    id: 35,
    code: "233",
    name: "TURISMO",
    faculty: null,
  },
  {
    id: 36,
    code: "427",
    name: "PSICOLOGÍA",
    faculty: null,
  },
];
