export const fakeStudents = [
  {
    id: 1,
    document_type: "001",
    document_number: "00000001",
    name: "John",
    paternal_surname: "Doe",
    maternal_surname: "Smith",
    student_code: "202001",
    career_code: "001",
    career_name: "ADMINISTRACIÓN",
  },
  {
    id: 2,
    document_type: "001",
    document_number: "00000002",
    name: "Jane",
    paternal_surname: "Doe",
    maternal_surname: "Smith",
    student_code: "202002",
    career_code: "002",
    career_name: "ANTROPOLOGÍA",
  },
  {
    id: 3,
    document_type: "001",
    document_number: "00000003",
    name: "Mary",
    paternal_surname: "Coe",
    maternal_surname: "White",
    student_code: "202003",
    career_code: "003",
    career_name: "ARQUITECTURA Y URBANISMO",
  },
  {
    id: 4,
    document_type: "001",
    document_number: "00000004",
    name: "Peter",
    paternal_surname: "Foe",
    maternal_surname: "Black",
    student_code: "202004",
    career_code: "004",
    career_name: "ARTE",
  },
  {
    id: 5,
    document_type: "001",
    document_number: "00000005",
    name: "Paul",
    paternal_surname: "Goe",
    maternal_surname: "Brown",
    student_code: "202005",
    career_code: "008",
    career_name: "BIOLOGÍA",
  },
  {
    id: 6,
    document_type: "001",
    document_number: "00000006",
    name: "George",
    paternal_surname: "Hoe",
    maternal_surname: "Green",
    student_code: "202006",
    career_code: "011",
    career_name: "CIENCIAS CONTABLES",
  },
  {
    id: 7,
    document_type: "001",
    document_number: "00000007",
    name: "Ringo",
    paternal_surname: "Joe",
    maternal_surname: "Blue",
    student_code: "202007",
    career_code: "012",
    career_name: "CIENCIAS DE LA COMUNICACIÓN SOCIAL",
  },
  {
    id: 8,
    document_type: "001",
    document_number: "00000008",
    name: "Stuart",
    paternal_surname: "Koe",
    maternal_surname: "Yellow",
    student_code: "202008",
    career_code: "013",
    career_name: "CIENCIAS FÍSICO MATEMÁTICAS",
  },
  {
    id: 9,
    document_type: "001",
    document_number: "00000009",
    name: "David",
    paternal_surname: "Loe",
    maternal_surname: "Orange",
    student_code: "202009",
    career_code: "015",
    career_name: "DERECHO",
  },
  {
    id: 10,
    document_type: "001",
    document_number: "00000010",
    name: "Mick",
    paternal_surname: "Moe",
    maternal_surname: "Red",
    student_code: "202010",
    career_code: "034",
    career_name: "EDUCACIÓN FÍSICA",
  },
  {
    id: 11,
    document_type: "001",
    document_number: "00000011",
    name: "Keith",
    paternal_surname: "Noe",
    maternal_surname: "Violet",
    student_code: "202011",
    career_code: "035",
    career_name: "EDUCACIÓN INICIAL",
  },
  {
    id: 12,
    document_type: "001",
    document_number: "00000012",
    name: "Charlie",
    paternal_surname: "Ooe",
    maternal_surname: "White",
    student_code: "202012",
    career_code: "036",
    career_name: "EDUCACIÓN PRIMARIA",
  },
  {
    id: 13,
    document_type: "001",
    document_number: "00000013",
    name: "Bill",
    paternal_surname: "Poe",
    maternal_surname: "Black",
    student_code: "202013",
    career_code: "037",
    career_name: "EDUCACIÓN SECUNDARIA",
  },
  {
    id: 14,
    document_type: "001",
    document_number: "00000014",
    name: "Brian",
    paternal_surname: "Qoe",
    maternal_surname: "Brown",
    student_code: "202014",
    career_code: "041",
    career_name: "ENFERMERÍA",
  },
  {
    id: 15,
    document_type: "001",
    document_number: "00000015",
    name: "Roger",
    paternal_surname: "Roe",
    maternal_surname: "Green",
    student_code: "202015",
    career_code: "042",
    career_name: "INGENIERÍA AGRÍCOLA",
  },
];
